/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agile.board;



import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

import com.agile.board.Application;

/**
 * Test Class for main Application
 * @author manjirilakhote
 *
 */
@SpringBootTest
public class ApplicationTest {
    @Test 
    public void healthCheckTest() {
        Application applicationTest = new Application();
        assertTrue("Health Ok".equals(applicationTest.healthCheck()));
        
    }
}
