/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.agile.board;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = "com.agile.board")
public class Application {
   
	public String healthCheck() {
		return "Health Ok";
	}
	
	public static void main(String[] args) {
		
	}
}
